# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  basic2:
    image: basic2
    build:
      context: .
      dockerfile: Basic2/Dockerfile
    ports:
      - 5000:5000
